### ISSUE TITLE
License? Storage?

### ISSUE THREAD

**Issue by webkenny** [namshi/notificator#24]
This looks like a really nifty library that fits into a REST service I am building but I don't see any `LICENSE` attached to it. Is this open source? I'm assuming so but want to ensure I follow the proper use and attribution depending on the license.

Also, just curious. How would you handle persisting the notifications? i.e. I use this library and want to persist the notifications I send so that they can be read at a later time (think Facebook). Do you think it would be wise to use a handler for that or is that only for broadcasting the messages?

Nice work, here, by the way. Very well thought out.

**Comment by odino** [comment]
Hey @webkenny extra-apologies for such a delayed reply, I have never seen this issue -- better now than never :)

1. it's released under [MIT license](https://packagist.org/packages/namshi/notificator)
2. the handler can save them in a persistent storage, then will be displayed from that storage by whoever is rendering the frontend

again, sorry for the delay :-D
