### ISSUE TITLE
Change @all to @here in hipchat example

### ISSUE THREAD

**Issue by funkytaco** [namshi/notificator#25]
I'm guessing this wouldn't message my whole organization, but it does consist of thousands of users, so I'd recommend switching @all to @here in the hipchat example.

I can just see some poor soul doing this after changing the chat room name and getting in trouble or fired.

**Comment by funkytaco** [comment]
No pulse on this project. Closing issue.

**Comment by odino** [comment]
hey @funkytaco, I missed this one earlier -- thanks for bringing it up!
