### ISSUE TITLE
implement a notificator bundle gluing the library to the heart of symfony with factories for notificators and managers

### ISSUE THREAD

**Issue by cordoval** [namshi/notificator#4]

**Comment by cordoval** [comment]
so sorry about this 😊 good that you close it

**Comment by odino** [comment]
no worries :)

On Mon, Apr 25, 2016 at 10:43 PM, Luis Cordova <notifications@github.com>
wrote:

> so sorry about this 😊 good that you close it
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/namshi/notificator/issues/4#issuecomment-214475525>
>



-- 
Nadalin Alessandro
http://www.linkedin.com/in/alessandronadalin
www.odino.org
www.twitter.com/_odino_
